src/django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('projects.urls', namespace='projects')),
    path("__debug__/", include("debug_toolbar.urls")),

    path('api/', include('api_projects.urls')),
]

src/projects/urls.py
from django.urls import path

from .views import MainPage, TaskDelails, AddComment

app_name = 'projects'

urlpatterns = [
    path('', MainPage.as_view(), name='main_page'),
    path('task/<pk>/', TaskDelails.as_view(), name='task_details'),
    path('task/<pk>/comment/', AddComment.as_view(), name='add_comment'),
]

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <title>{{ title }}</title>
</head>

<body>
  <header class="header">
    <div class="container">
      <nav class="header-nav">
        <h1>{{ title|capfirst }}</h1>
        {% if title == 'Главная страница' %}
        <a class="logo">
          <img src="{% static 'logo.svg' %}" alt="лого" class="logo-img">
        </a>
        {% else %}
        <a class="main-page-link" href="{% url 'projects:main_page' %}">Главная страница</a>
        {% endif %}
      </nav>
    </div>
  </header>
  <main class="main">
    <div class="container">
      {% block content %}
      {% endblock %}

      {% block comments %}
      {% endblock %}

      {% block navigation %}
      {% endblock %}
    </div>
  </main>
</body>

</html>