src/django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('projects.urls', namespace='projects')),
    path("__debug__/", include("debug_toolbar.urls")),

    path('api/', include('api_projects.urls')),
]

src/projects/urls.py
from django.urls import path

from .views import MainPage, TaskDelails, AddComment

app_name = 'projects'

urlpatterns = [
    path('', MainPage.as_view(), name='main_page'),
    path('task/<pk>/', TaskDelails.as_view(), name='task_details'),
    path('task/<pk>/comment/', AddComment.as_view(), name='add_comment'),
]

src/projects/models.py
from django.db import models
from django.urls import reverse


class ProjectQuerySet(models.QuerySet):
    def filter_projects(self, flag: str | None) -> models.QuerySet:
        match flag:
            case '1':
                return self.filter(is_active=True)
            case '0':
                return self.filter(is_active=False)
            case _:
                return self


class Project(models.Model):
    name = models.CharField('Название', max_length=255, db_index=True)
    description = models.TextField('Описание')
    is_active = models.BooleanField('Активен?', default=True)

    objects = ProjectQuerySet.as_manager()

    def __str__(self) -> str:
        return f'{self.name} - активен?: {self.is_active}'

    class Meta:
        verbose_name = 'Проект'
        verbose_name_plural = 'Проекты'

    def get_absolute_url(self):
        return reverse('projects:main_page')


class TaskQuerySet(models.QuerySet):
    def get_all_joins(self):
        return self.prefetch_related('comments', 'employees').select_related('project')


class Task(models.Model):

    class TaskStatus(models.TextChoices):
        NEW = 'NEW', 'Новая'
        IN_PROCESS = 'IN_PROCESS', 'В работе'
        CLOSED = 'CLOSED', 'Закрыта'

    name = models.CharField('Название', max_length=255, db_index=True)
    deadline = models.DateField('Срок исполнения')
    description = models.TextField('Описание')
    status = models.CharField(
        'Статус задачи',
        max_length=20,
        choices=TaskStatus.choices,
        default=TaskStatus.NEW,
        db_index=True,
    )
    project = models.ForeignKey(
        Project,
        on_delete=models.CASCADE,
        related_name='tasks',
        verbose_name='Проект',
    )

    objects = TaskQuerySet.as_manager()

    def __str__(self) -> str:
        return f'{self.name} - {self.deadline}'

    class Meta:
        verbose_name = 'Задача'
        verbose_name_plural = 'Задачи'

    def get_absolute_url(self):
        return reverse('projects:task_details', kwargs={'pk': self.id})


class Employee(models.Model):
    name = models.CharField('ФИО сотрудника', max_length=255)
    position = models.CharField('Должность', max_length=255)
    tasks = models.ManyToManyField(
        Task,
        related_name='employees',
        verbose_name='Задачи',
    )

    def __str__(self) -> str:
        return self.name

    class Meta:
        indexes = [models.Index(fields=['name'])]
        verbose_name = 'Сотрудник'
        verbose_name_plural = 'Сотрудники'


class Comment(models.Model):
    text = models.TextField('Tекст')
    written_in = models.DateTimeField('Дата написания', auto_now_add=True)
    task = models.ForeignKey(
        Task,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Задача',
    )

    def __str__(self) -> str:
        return f'Написан в {self.written_in}'

    class Meta:
        ordering = ['-written_in']
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

src/projects/forms.py
from django import forms

from .models import Comment


class CommentForm(forms.Form):
    text = forms.CharField(
        label='Комментарий',
        widget=forms.Textarea(attrs={'rows': 3, 'class': 'form-control'}),
    )

src/projects/views.py
from typing import Any

from django.db.models.base import Model as Model
from django.db.models.query import QuerySet
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import ListView, DetailView, View
from django.http.request import HttpRequest
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse
from django.conf import settings

from .models import Project, Task, Comment
from .forms import CommentForm


class MainPage(ListView):
    template_name = 'index.html'
    context_object_name = 'projects'
    paginate_by = settings.PAGINATE_BY
    allow_empty = False
    extra_context = {'title': 'Главная страница'}

    def get_queryset(self) -> QuerySet[Any]:
        project_filter = self.request.GET.get('is_active')
        return Project.objects.filter_projects(project_filter).prefetch_related('tasks')

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        projects_filter = [
            ['?', 'Все проекты'],
            ['?is_active=1', 'Активные'],
            ['?is_active=0', 'Не активные'],
        ]
        context['projects_filter'] = projects_filter
        return context


class TaskDelails(DetailView):
    template_name = 'task_details.html'
    context_object_name = 'task'
    pk_url_kwarg = 'pk'

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['title'] = f'Задача: {context.get("task").name}'
        context['form'] = CommentForm()
        return context

    def get_object(self, queryset: QuerySet[Any] | None = ...) -> Model | None:
        obj = Task.objects.get_all_joins().filter(id=self.kwargs[self.pk_url_kwarg]).first()
        if not obj:
            raise Http404
        return obj


class AddComment(View):
    def post(self, request: HttpRequest, pk: int) -> HttpResponseRedirect:
        form = CommentForm(request.POST)
        task = get_object_or_404(Task, id=pk)
        if form.is_valid():
            Comment.objects.create(**form.cleaned_data, task=task)
            return redirect(reverse('projects:task_details', kwargs={'pk': pk}))

src/projects/templates/index.html
{% extends 'base.html' %}

{% block content %}

<details data-filter-title="Фильтр проектов" open>
  <summary>
    Фильтр проектов
  </summary>
  <ul>
    {% for pr_filter in projects_filter %}
    <li>
      <a href="{{pr_filter.0}}">{{pr_filter.1}}</a>
    </li>
    {% endfor %}
  </ul>
</details>

{% for project in projects %}
<div class="card text-left">
  <h5 class="card-header text-center">{{ project.name|capfirst }}</h5>
  <div class="card-body">
    <p class="card-text">{{ project.description|truncatewords:20 }}</p>
    {% for task in project.tasks.all %}
    <a href="{{ task.get_absolute_url }}" class="btn btn-primary">{{ task.name|truncatechars:12 }}</a>
    {% endfor %}
  </div>
  <div class="card-footer text-muted">
    {% if project.is_active %}
    Проект активен
    {% else %}
    Проект неактивен
    {% endif %}
  </div>
</div>
{% endfor %}

{% endblock %}


{% block navigation %}

{% if page_obj.has_other_pages %}
<ul class="pagination">
  {% if page_obj.has_previous %}
  <li class="page-item">
    <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
      <span aria-hidden="true">&laquo;</span>
    </a>
  </li>
  {% endif %}
  {% for page in paginator.page_range %}
  {% if page_obj.number == page %}
  <li class="page-item">
    <a class="page-link current-page">{{ page }}</a>
  </li>
  {% elif page >= page_obj.number|add:-2 and page <= page_obj.number|add:2 %} <li class="page-item">
    <a class="page-link" href="?page={{ page }}">{{ page }}</a>
    </li>
    {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
    {% endif %}
</ul>
{% endif %}

{% endblock %}

src/projects/templates/task_details.html
{% extends 'base.html' %}

{% block content %}
<div class="card text-center">
  <div class="card-header">
    <h5>{{ task.name|capfirst }}</h5>
  </div>
  <div class="card-body">
    <div class="inner-card-body">

      <p class="card-text">{{ task.description }}</p>

      <ul class="task-block">
        {% if task.employees.all %}

        {% if task.project.is_active %}
        <h5>Над задачей работают:</h5>
        {% else %}
        <h5>Над задачей работали:</h5>
        {% endif %}

        {% for employee in task.employees.all %}
        <li>{{ employee.name }}</li>
        {% endfor %}
        {% else %}
        <h5>Над задачей пока никто не работает</h5>
        {% endif %}
      </ul>

    </div>
  </div>
  <div class="card-footer text-muted">
    <p>Статус задачи: {{ task.get_status_display }}</p>
    <p>Срок исполнения: {{ task.deadline }}</p>
    <p>Проект: {{ task.project.name|capfirst }}</p>
  </div>
</div>
{% endblock %}

{% block comments %}

<form action="{% url 'projects:add_comment' pk=task.id %}" method="post">
  {% csrf_token %}
  <div class="form-error">{{ form.non_field_errors }}</div>
  {% for field in form %}
  <div class="mb-3">
    <label class="form-label" for="{{ field.id_for_label }}">{{ field.label }}:</label>{{ field }}
  </div>
  <div class="form-error">{{ field.errors }}</div>
  {% endfor %}
  <p><button class="btn btn-primary btn-comment" type="submit">Отправить</button></p>
</form>

{% for comment in task.comments.all %}
<div class="card">
  <div class="card-body">
    <h6 class="card-subtitle mb-2 text-muted">{{ comment.written_in }}</h6>
    <p class="card-text">{{ comment.text }}</p>
  </div>
</div>
{% endfor %}
{% endblock %}